spring.application.name=lab7_6733804228_sec3

#db connection
spring.datasource.url=jdbc:postgresql://localhost:5432/lab7
spring.datasource.username=postgres
spring.datasource.password=p@ssword

# db setting
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
